result = input().split(' ')
print(int(result[0]) + int(result[1]))
print(int(result[0]) - int(result[1]))
print(int(result[0]) * int(result[1]))
print(int(result[0]) // int(result[1]))
print(int(result[0]) % int(result[1]))